# Generated by Django 2.1.4 on 2019-01-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_auto_20190105_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='quantity',
        ),
        migrations.AddField(
            model_name='handles',
            name='quantity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
