# Generated by Django 2.1.4 on 2019-01-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_auto_20190105_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='handles',
            name='totalprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
