# Generated by Django 2.1.4 on 2019-01-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0008_handles_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('photos', models.TextField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('totalprice', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
