# Generated by Django 2.1.4 on 2019-01-06 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0010_auto_20190106_0119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doors',
        ),
    ]
