# Generated by Django 2.1.4 on 2019-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0012_doors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedroom_doors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photos', models.TextField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('totalprice', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom_handles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photos', models.TextField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('totalprice', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hall_doors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photos', models.TextField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('totalprice', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hall_handles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photos', models.TextField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('totalprice', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Wardrobe',
            new_name='Bedroom',
        ),
    ]
