# Generated by Django 2.1.4 on 2019-01-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0013_auto_20190109_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroom',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchen',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
